### ISSUE TITLE
IRC/Chat redirect issue

### ISSUE THREAD

**Issue by Noahkiq** [PugaBear/website#10]
The Chat button on the nav bar goes to a https:// site, while it should be http://
![image](https://cloud.githubusercontent.com/assets/13265322/16433464/59a8329e-3d58-11e6-9782-308eedfeca5d.png)
how dare you be trying to steal my passwords, messages, or credit cards!!!one!1one

**Comment by PugaBear** [comment]
oops, my secret is out

**Comment by Noahkiq** [comment]
closed it before you hehe

**Comment by Noahkiq** [comment]
>:(
