### ISSUE TITLE
Application page oddities

### ISSUE THREAD

**Issue by Noahkiq** [PugaBear/website#11]
_i know the applications & such are still WIP, but i'm putting this stuff here anyway_

1. It acts like the vote page.
![image](https://cloud.githubusercontent.com/assets/13265322/16433584/02fe9928-3d59-11e6-8ae1-8b847b9c795b.png)
2. ~~When clicking on the "Ban Appeals" button, it keeps the color of the mouseover/click until you click on "Moderator Application" or refresh the page. [Screenshot (gif)](http://i.imgur.com/H1WwyRk.gifv)~~ fixed

**Comment by PugaBear** [comment]
Made it open in the same page. Thank ya

**Comment by Noahkiq** [comment]
Not sure if intentional, but there's now a big gap in between the "Applications - coming soon!" button-text-thing and the actual application buttons
![image](https://cloud.githubusercontent.com/assets/13265322/16434060/76e0acda-3d5b-11e6-9697-0fdd0ca3836b.png)

**Comment by Noahkiq** [comment]
original size for context
![image](https://cloud.githubusercontent.com/assets/13265322/16434399/8fd8e8ae-3d5d-11e6-9b95-7aad382117ff.png)

**Comment by PugaBear** [comment]
Added that on purpose

**Comment by Noahkiq** [comment]
I thought it was fine, just didn't know if it was intentional or not.

**Comment by PugaBear** [comment]
Alright. I just wanted to separate the header and the buttons, cause they look kinda similar- didnt want people clicking on the header and being confused. I might change the header more later on.
