### ISSUE TITLE
Help page in footer

### ISSUE THREAD

**Issue by Noahkiq** [PugaBear/website#12]
Found some more weird things while looking at the bottom bar thing.
1. ~~There's a button that shows how long the page took to load, which lets you click on it, but just sends you to the top of the page. [Screenshot (GIF)](http://i.imgur.com/ZmfWZgs.gifv)~~ fixed
2. There's a generic help page not currently being used for anything
3. ~~When clicking on "© Bear Nation 2016", it brings up another thing saying "Site software © Samerton", which when clicking on that, it re-opens the page you are currently on in a new tab. [Screenshot (GIF)](http://i.imgur.com/EXc9lWT.gifv)~~ now opens namelessMC github page in a new tab

**Comment by PugaBear** [comment]
Ive noticed all these things, and the copyright is there to credit the author of the original site software. The help page will likely redirect to the wiki, thats something I'll have to discuss with staff. And the page loading thing, I'll look into that not being a button.

**Comment by PugaBear** [comment]
Fixed the tachometer.

**Comment by Noahkiq** [comment]
I know why the copyright is there, I was just pointing out that the Samerton copyright thing is clickable and brings you back to the top of the page.

**Comment by PugaBear** [comment]
Irrelevant now
