### ISSUE TITLE
Bugs, bugs, and more bugs.

### ISSUE THREAD

**Issue by Noahkiq** [PugaBear/website#18]
- (Forum) There's a "Home" button at the top of the page.
![image](https://cloud.githubusercontent.com/assets/13265322/17823434/7c85164c-662a-11e6-9f9f-5b91a3ed2321.png)
- There's 3 help buttons (at the bottom of every page). I don't think anybody needs _that_ much help.
![image](https://cloud.githubusercontent.com/assets/13265322/17823597/4988da16-662b-11e6-9c1e-30c7a95b8dd4.png)
- ~~(Status Page) "And X More" isn't clickable. (unless it never was but i swear you could click it at one point)~~ apparently it was never clickable.
- (Forum Search) You can view posts you're not supposed to see.
![image](https://cloud.githubusercontent.com/assets/13265322/17823711/ebe896e8-662b-11e6-9668-a00c573d47e3.png)
- (Forum Search) This doesn't look normal.
![image](https://cloud.githubusercontent.com/assets/13265322/17823721/fa8941e8-662b-11e6-931d-4d3115edbec2.png)
- (User Profile) No friend button. (maybe i'm blind?)
![image](https://cloud.githubusercontent.com/assets/13265322/17823819/911e2f10-662c-11e6-97a4-dc61776b838f.png)

Extra:
- (Applications) Mod apps still isn't clickable. It also still says this.
![image](https://cloud.githubusercontent.com/assets/13265322/17823768/41848c60-662c-11e6-8f3e-245db511ee31.png)

**Comment by PugaBear** [comment]
Fixed all of them, there's no friend button but there's an "unfollow" button, and it isnt clickable because its coming soon(tm). :P
