### ISSUE TITLE
Navigation bar issues

### ISSUE THREAD

**Issue by Noahkiq** [PugaBear/website#26]
- Hovering over any item makes the icon next to the item's text highlight before the text ~~which is really annoying~~ - [GIF](http://i.imgur.com/Kwggwcb.gif)
- The icons in the "More" submenu are always highlighted.
  ![image](https://cloud.githubusercontent.com/assets/13265322/19496542/eca140fe-9555-11e6-896b-020bfea087f7.png)
- Pages that link to an external website open the site in a new tab. (could be intended but i dont remember this happening before)

**Comment by PugaBear** [comment]
- Not even sure how to change the hover delay on the text, but I kinda like it. oops? 

- I'll fix those icons

- http://uxmovement.com/navigation/why-external-links-should-open-in-new-tabs/ tl;dr if the site you are linking to does not include the navbar of the page it should open in a new tab. widely accepted website development principal. it's not that way on enjin cause enjin isnt smart enough.

**Comment by Noahkiq** [comment]
- _dont have anything to say_

- 👍 

- Fair enough.
