### ISSUE TITLE
Countdown issues

### ISSUE THREAD

**Issue by Noahkiq** [PugaBear/website#29]
this is probably going to be the last thing i post but

- Title of countdown page is "vote", and the vote button on the navbar is highlighted orange
![Countdown title error](http://i.imgur.com/ivGmUPl.png)
![Navbar error](https://cloud.githubusercontent.com/assets/13265322/20863630/d10bf7ae-b99e-11e6-9ad6-c90769a7fa97.png)

- Double countdown
![Double countdown](https://cloud.githubusercontent.com/assets/13265322/20863631/e9364802-b99e-11e6-8c82-e1bb0d416357.png)

**Comment by PugaBear** [comment]
I hadnt even finished it yet so :p
