### ISSUE TITLE
No hat layer next to username

### ISSUE THREAD

**Issue by Noahkiq** [PugaBear/website#3]
In the top right corner of the site, you can see your username and your in-game face, but the hat layer is not shown.

- Confirmed for PC (top right) & Mobile (dropdown menu)
- Using Chrome (PC & Mobile)
- [Picture](http://i.imgur.com/hLuB5Q7.png)

**Comment by Noahkiq** [comment]
I saw that cravatar was being used, so [this should fix it](http://i.imgur.com/SZOnYpi.png).

**Comment by PugaBear** [comment]
Solved
