### ISSUE TITLE
2FA - "NamelessMC" + Broken 2FA

### ISSUE THREAD

**Issue by Noahkiq** [PugaBear/website#4]
The name of the application in my authentication app is "NamelessMC"

- Confirmed on PC (Chrome)
- [Screenshot](http://i.imgur.com/sH1o8j0.png)
- To reproduce:
  - Go to your user settings (Name of the page is "UserCP", is that a bug?)
  - Enable 2FA (Phone)
  - Scan the QR code shown in an authenticator app
  - Look at the name, it says "NamelessMC"

**also 2FA doesn't actually work (tested QR code & text code), always says invalid code, so you can't actually turn it on**

**Comment by Noahkiq** [comment]
can confirm email 2FA works

**Comment by PugaBear** [comment]
Replicated with Auth App.

User CP is not a bug- its an abbreviation for User Control Panel. I can change that though.
NamelessMC is the software that runs the app. I wonder if I can change that, too.

Will look into it, thanks.

**Comment by Noahkiq** [comment]
Might want to post the broken 2FA part in https://github.com/NamelessMC/Nameless/issues

**Comment by PugaBear** [comment]
Meant to, got lazy :p

**Comment by PugaBear** [comment]
https://github.com/NamelessMC/Nameless/issues/289
