### ISSUE TITLE
Nav bar additions

### ISSUE THREAD

**Issue by Noahkiq** [PugaBear/website#7]
Some of the things from the enjin nav bar that haven't been added yet:
- Store
- Gallery
- ~~Chat/IRC~~ 
- ~~Wiki~~
- ~~Applications~~

**Comment by PugaBear** [comment]
Wanna search around for a gallery type software?

**Comment by Noahkiq** [comment]
I found [this](http://piwigo.org/), and I think that's what you're looking for, but I'm not sure.

**Comment by PugaBear** [comment]
Piwigo looks great, thank you :)

**Comment by PugaBear** [comment]
Moving to new issue
